import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get('theme')
  return (
    <html lang="en" className={`${theme?.value ? theme.value : 'light'}`} style={{scrollBehavior: 'smooth'}}>
      <body className='bg-gray-100  dark:bg-gray-950'>{children}</body>
    </html>
  );
}
